### ISSUE TITLE
Thorium Ungoogled edition

### ISSUE THREAD

**Issue by al3xxx** [Alex313031/thorium#115]
Hello Alex,
Is there any chance for thorium ungoogled edition?

**Comment by DI555** [comment]
yes, double that, but might better to skip using ungoogled patches at all, i mean totally in Thorium!

**Comment by ms178** [comment]
If there were only a source PKGBUILD for the AUR which could be customized for a couple of special flavors, it would lessen the burden on Alex to maintain too much versions himself and offer the flexibility that people could try out their favored Thorium flavor.

**Comment by Alex313031** [comment]
@al3xxx @DI555 @ms178 Thorium already uses some patches from ungoogled chromium, however one of my philosophies was to not hamper usability. So I have not included any patches that disable the web store, google search, or sync. However, privacy and security patches, including removing things that "phone home" to google (besides the bare minimum to make the above things work properly), have been integrated. I don't plan on making an ungoogled thorium, because that is alot of extra work. However, if you wanted to make an ungoogled build with the compiler optimizations of thorium, one could just set up a normal ungoogled build, but before actually compiling, copy this dir over the chromium tree > https://github.com/Alex313031/thorium/tree/main/src/build/config

**Comment by ms178** [comment]
@al3xxx @DI555 You might want to modify the PKGBUILD of that Ungoogled Chromium package: https://aur.archlinux.org/packages/ungoogled-chromium

It is a source package, so compiling Chromium yourself might take a while.

**Comment by DI555** [comment]
@Alex313031 , could you pls integrate to Thorium and all flagged ungoogled chromium patches (i mean those with flags)???
they all - are optional/switchable , cause all have flags, and very usefull - like uncrypted profile for portable using, for example!..

**Comment by Intellectual234** [comment]
Hey @DI555 , I cant find a way to message you, can we talk to each other about privacy, browsers, cyber security,etc? I know a lot about Thorium,etc. Heres my email: my_email111111@protonmail.com

**Comment by DI555** [comment]
@gz83 , but why not? - theese flags are great features for browser, really GREAT features!!!

**Comment by rmdhnreza** [comment]
Any chance adds `disable qr`, `remove tabsearch` & `Omnibox Autocomplete Filtering` flags? I know many people use that features, but I used Ungoogled Chromium because the flags are really useful for me.

**Comment by Flashwalker** [comment]
If any patches have been applied, they are clearly not enough https://github.com/Alex313031/thorium/discussions/119#discussioncomment-5275895

IMHO connections to any Google domain/service should only be made explicitly on demand.
