### ISSUE TITLE
Alex said there would be an "Are you sure?" popup browser exit flag option added to newest release, I cant find it.

### ISSUE THREAD

**Issue by Intellectual234** [Alex313031/thorium#120]
I checked the 45th Release notes & I cant find any mentioning of this flag that Alex speaks of. What is the name of this flag
so that I can search for it & find it?

Also, does thorium keep all browser history, instead of merely for 90 days? does thorium keep it all forever, by default?

And does thorium force handle .crx file,force installing extensions by default? is this a good idea?

**Comment by Intellectual234** [comment]
@gz83 , alex just said they were added? https://github.com/Alex313031/Thorium-Win/issues/28#issuecomment-1455050050

**Comment by Alex313031** [comment]
@Intellectual234 Im sorry. I was going to add it, however gz83 brought up an issue with localization. But @gz83 I think I can add that patch now, and we can worry about localization later, so we can get it out for him sooner. 

@Intellectual234 What platform are you using thorium on, so that I can make a release only for that, and just swap out the releases (i.e. not make a new release, but just edit the current one and delete/reupload the new one once it is built)

**Comment by Intellectual234** [comment]
Right now I'm using thorium-browser_110.0.5481.178_amd64.deb for ZorinOS. Thorium's 45th release.
And thank you for modifying it :)

**Comment by Intellectual234** [comment]
@gz83 , @Alex313031 , so when can i expect to be able to use a browser exit confirmation flag?

**Comment by Alex313031** [comment]
@Intellectual234 I added the flag, however it is only live in this linux build. Im gonna be making a Windows SSE3 build next. If you want an AVX or AVX2 build with the flag, you will have to wait until next M111 release.

Here: https://github.com/Alex313031/Thorium-Special/releases/tag/M110.0.5481.179-1

**Comment by Intellectual234** [comment]
@Alex313031 , thank you buddy ol' pal! Whats the name of the flag exactly? so i can find it. :)
