### ISSUE TITLE
Consider changing the logo colour to resemble a thorium rock in colour?

### ISSUE THREAD

**Issue by LethalManBoob** [Alex313031/thorium#125]
as an example VVV 
![image](https://user-images.githubusercontent.com/30273211/224422625-43e0b6e5-bcb9-49a8-9b1c-6be5ddde68a8.png)

I find the current logo doesnt look appealing as such.

**Comment by Alex313031** [comment]
@LethalManBoob Thorium is not a rock. It is an element. There are many minerals that contain Thorium, usually alongside Uranium, as uranium decay produces thorium. Heres a picture of the actual element which this browser is named after > 

As a side note, that picture is actually from theodore gray, the person who made this book > https://www.google.com/books/edition/Elements/gICDBAAAQBAJ?hl=en&gbpv=1&dq=theodore+gray+elements&printsec=frontcover and this website > https://periodictable.com/theelements/pages.html

He is actually what got me interested in Chemistry and the elements, and why thorium is named the way it is, which I also highlight in the readme.

But anyway, going off of either the rock or the pure element, what were you having in mind. Are you talking about the black inner ring? Because that is the only difference between the chromium logo and the thorium logo?

@midzer @gz83 What do you think of this?

**Comment by LethalManBoob** [comment]
It was just my opinion that the logo is too close to chromium to stand out. Was just suggesting a colour change.

**Comment by Alex313031** [comment]
@LethalManBoob Well that was kinda my goal lol. I wanted to make a chromium fork that increased performance, security, and usability, while still being recognizably chromium. Thats also why I havent modified the UI much, although Ive changed some UI icons and some chrome:// pages.

**Comment by LethalManBoob** [comment]
Yeah i get the idea of the chromium with some additions. I guys the black ring just looks a bit .. ugly? 
Again just my opinion but maybe it should be somthing else
![image](https://user-images.githubusercontent.com/30273211/224480331-dd950eec-0ddc-4bb4-96c6-b9d67fe107f5.png)
it kinda just looks like it doesn't belong

**Comment by Alex313031** [comment]
@LethalManBoob You can change the icon to whatever you want by changing the icons in /usr/local/share/icons/hicolor/ OR editing the Icon=thorium-browser line in /usr/share/applications/thorium-browser.desktop to the absolute path of a new icon. Icon should be in .svg format, or a .png of 48x48px or greater (but less than 512px)

**Comment by rubyFeedback** [comment]
I guess this would only be useful to discuss if the changed log looks better or so.

What I think speaks for the current logo is that it is simple. So I would definitely retain the original one.

IF a change should occur, e. g. if you want to make ti "rockier" or more "thorium-ore" like, I would still
recommend to keep the old structure as much as possible. So perhaps just the texture to be adapted
a bit. But even then I am not sure it is worth it.

IF the issue is about it being too similar to the chrome logo then perhaps you can adapt it a bit with
more texture. Googling for it for images (which is, oddly enough, still useful, more useful than 
regular text search nowadays), most images I see a more of an odd grayish-brown-beige tone.
Thorium as metal looks pretty cool though: https://upload.wikimedia.org/wikiversity/en/2/26/Thorium_metal.png 
a bit like quicksilver, isn't it? So perhaps a texture that would fit a bit to silver and darkbrown or
so. But, as said, I am not sure this should be done. Logos should ideally be simple and not too
confusing. I also think blue is better than brown or silver actually.

**Comment by badP0inter** [comment]
![Chromium_Logo 1](https://user-images.githubusercontent.com/51961935/226903447-ffd9f89e-4807-489e-9936-46e536a0c547.svg)
Threw together in a couple minutes, thank me later.

Here's my five cents:
  - Current logo looks *bad*. The pure black, combined with the fact that the outline used is an outside one makes it an eyesore in any environment it's shown in. Pure black never works, and you should opt for gray (#AAAAAA), silver (#DDDDDD), or if the situation calls for it, dark (#111111).
  - This is outside the scope of this issue, but the coloring of buttons used in the UI, too, looks *bad*. The issue is that these buttons aren't meant to have colors different from a dark gray to begin with. However, even if we ignore that, the colors being used are far too saturated. So, instead of opting for #69ffe6, you should opt for a shade like #33b597. But overall, I'm all for reverting the color changes in the UI.

**Comment by badP0inter** [comment]
Alternate version, had this idea today. I still prefer the first version, as it is more Chromium-like, but this is an interesting experiment, highlighting the actual form of these "leaves".
![Chromium_Logo 2](https://user-images.githubusercontent.com/51961935/227127103-23629330-0ec4-4a2b-b017-6aca8affb88c.svg)

**Comment by LethalManBoob** [comment]
Nice work badpoint.

**Comment by Alex313031** [comment]
@badP0inter I agree that the UI icons need to be improved. However, I dont think the pure black ring looks bad in thorium. But I can try and experiment with different shades of grey for the inner ring and see how it looks.
