### ISSUE TITLE
Sync not working - Windows 

### ISSUE THREAD

**Issue by petar-staynov** [Alex313031/Thorium#17]
I can't get Google Sync to work on neither the AVX M101.0.4918.0 or the AVX2 M101.0.4921.0 Windows build.
After clicking the "Turn On Sync" button and entering my Google account details, 
my account gets logged in into Google, but not the browser where it still says "Not Signed In"

**Comment by Alex313031** [comment]
@petar-staynov Even though this repo hosts the source code, you should put windows bugs in the windows repo or bugs on the avx2 build in that repo, not here.
Sync works for me, I'm using M101.0.4921.0.
Make sure to enable it by going into the settings and setting up sync, not after signing in on gmail or something. 
If it still doesn't work, it is possible that I used my personal API Keys in this build by mistake, rather than the public ones I set up for Thorium. In this case, use another release, or make sure you are subscribed to this google group https://groups.google.com/u/1/a/chromium.org/g/google-browser-signin-testaccounts as per https://www.chromium.org/developers/how-tos/api-keys/

If, after this, Sync still doesn't work, then I dont know.

**Comment by petar-staynov** [comment]
I made sure to try and set up sync from Settings, not from logging in any google site.

I tried **9th Release - M100.0.4888.0** and setting up Sync works correctly there.
Surprisingly after updating to **10th Release**, Sync was still working. 
I then updated to **2nd Release - M101.0.4921.0 - AVX2** and Sync still works.

It seems installing the 9th release and setting up sync there fixes the issue in the later builds.

**Comment by Alex313031** [comment]
@petar-staynov That is strange. Glad it worked for you. Can you try the portable M101.0.4921.0 .zip and run the thorium.bat in there and try sync in that with the fresh profile. Report if it doesn't work on that. You can just delete the folder after.

**Comment by petar-staynov** [comment]
Sync works there too. 
Maybe the issue I had was due to leftover files from previous Chromium installs.

**Comment by Alex313031** [comment]
@petar-staynov Ok closing this issue
