### ISSUE TITLE
Your Linux version have leaks

### ISSUE THREAD

**Issue by LeOS-GSI** [Alex313031/thorium#206]
I have tested your Linux version on Devuan. And it show several leaks hich needs to be removed.
https://results.privacytests.org/me?sessionId=1052138834946903

if the link does not work anymore, youcan test it by your own with https://privacytests.org/me.html

**Comment by Alex313031** [comment]
@LeOS-GSI I plan on adding GPC and disabling canvas fingerprinting. As far as cookies, better privacy can be enabled via chrome://flags. As far as anything more than that, I probably won't do it either because I don't know how, or because it would interfere with usability (see the goals at the top of the readme)
