### ISSUE TITLE
Serious bug: When the audio icon on the tab is clicked, the sound will be muted. Right-clicking on the tab shows that there is no mute (and the mute option is invalid)

### ISSUE THREAD

**Issue by Malus-risus** [Alex313031/thorium#214]
**System Details**
 - OS: Windows11 22621.2215
 - Thorium Version 116.0.5845.169

**Problem**
When the audio icon on the tab is clicked, the sound will be muted. Right-clicking on the tab shows that there is no mute (and the mute option is invalid). However, the icon on the tab is a mute icon. You can only restart the browser or click Mute icon solved!

**Screenshots**
![image](https://github.com/Alex313031/thorium/assets/69906215/f125dadf-de62-46c2-ba08-61bf42f635f5)

**Additional Notes**
I've reinstalled the browser and it still doesn't work.

**Comment by gz83** [comment]
I don't think this is a bug, the Thorium browser hasn't changed the code involved in this feature, and the logic is the same in the upstream version.

You could consider raising an issue with Google in crbug and see if Google engineers would consider changing this feature, but since it's about user experience and user actions, I don't think Google would change it so easily because changes that involve user experience and user actions have to be discussed and approved by UX engineers before they can be changed.

I think it would be more convenient to click the horn shaped button directly on the tab to control mute or unmute.

@Cryberghost

**Comment by Alex313031** [comment]
@Cryberghost Yeah this is upstream, it has behaved like this for as long as they have had the tab mute button feature. It is annoying, but not something on my end.

**Comment by Cryberghost** [comment]
> I don't think this is a bug, the Thorium browser hasn't changed the code involved in this feature, and the logic is the same in the upstream version.
> 
> You could consider raising an issue with Google in crbug and see if Google engineers would consider changing this feature, but since it's about user experience and user actions, I don't think Google would change it so easily because changes that involve user experience and user actions have to be discussed and approved by UX engineers before they can be changed.
> 
> I think it would be more convenient to click the horn shaped button directly on the tab to control mute or unmute.
> 
> @Cryberghost

When there are so many tabs, this button is not clickable.

**Comment by gz83** [comment]
We may consider adding an unmute function to the tab's right-click menu, but don't expect this function to definitely appear in the new version.

@Cryberghost

**Comment by rubyFeedback** [comment]
Semi-related to this, I often misclick on the mute-icon accidentally. This happens when I have too many tabs open.

Going the reverse, e. g. unmuting, is much easier than muting. I think this is a tiny UI deficit. It's not really hugely important to me but it would be nice if that handling would be simplified (I actually don't need the mute functionality at all anyway; I either stop the video such as when it is on youtube in the play-view widget, or decrease the volume of my speakers, so to me personally it is more of an anti-feature. I tried to find a setting called "mute" to disable this completely but could not find it. Would be nice if disabling this feature altogether would be easier too)

**Comment by gz83** [comment]
You can remove the mute button on the tab by turning off the following experimental feature flags

chrome://flags/#enable-tab-audio-muting

@rubyFeedback

**Comment by mrrahmatt** [comment]
> You can remove the mute button on the tab by turning off the following experimental feature flags
> 
> chrome://flags/#enable-tab-audio-muting
> 
> @rubyFeedback

very usefull, thanks
