### ISSUE TITLE
Build instructions missing submodule instructions

### ISSUE THREAD

**Issue by qoijjj** [Alex313031/thorium#219]
**System Details**
 - OS: [e.g.  Ubuntu 22.04, Windows 7, 8.1, 10, 11]
 - Thorium Version [e.g.107.0.5347.0]

**Problem**

Build instructions don't specify to initialize and update submodules for thorium-libjxl, which is required for running version.sh

```
git submodule init
git submodule update
```

**Screenshots**

**Additional Notes**

**Comment by gz83** [comment]
Are you really familiar with how to compile chromium? Also, have you checked the compilation guidelines? Instead of using these git commands to get and update submodules, we use commands such as fetch and gclient in depot_tools to get source code, update checkout, get and update submodules, etc.

https://github.com/Alex313031/thorium/tree/main/docs

@qoijjj

**Comment by qoijjj** [comment]
@gz83 I followed the instructions verbatim, including the fetch and gclient commands. They did not populate the submodule properly.

**Comment by qoijjj** [comment]
and to clarify this is specifically for  thorium-libjxl submodule, not the others

**Comment by gz83** [comment]
Just add the --recursive parameter to the command to clone thorium's repo to pull the submodule.

When the submodule is updated, the thorium repo will also be updated synchronously.

@qoijjj

**Comment by qoijjj** [comment]
@gz83 yes, my point is that that should be reflected here:

https://github.com/Alex313031/thorium/blob/3351465f2bdea7b724ea4338eea3f90d2559772e/docs/BUILDING.md?plain=1#L45

**Comment by qoijjj** [comment]
https://github.com/Alex313031/thorium/pull/220

**Comment by qoijjj** [comment]
fixed in https://github.com/Alex313031/thorium/pull/220
