### ISSUE TITLE
Fedora copr?

### ISSUE THREAD

**Issue by arun54321** [Alex313031/Thorium#29]
Could you add Fedora copr?

**Comment by Alex313031** [comment]
@arun54321 The Thorium portable .zips work well for other distros. I've tested it on Arch, Gentoo, Fedora, and CentOS.

I don't really use fedora, so I don't know what the COPR is but google search shows it is kind of like the AUR in arch. I dont know how I would go about adding it to there. 

I'm already building alot for linux, windows, and windows avx2, as well as making personal builds, so having to also build RPM packages is alot of work considering that the portable zips work fine, you just have to modify/copy the .desktop files to wherever you want to put Thorium, which is more work than the seamless desktop integration of installing a .deb/.rpm/.pkg, but once you do it, then you just have to unpack future updates wherever you put Thorium.

Sorry if this isn't the answer you were wanting. Perhaps when I get a faster machine and/or more people to build (@midzer midzer makes the macos/tigerlake releases and @gz83 very recently started making windows avx2 releases since my haswell board died), then I would consider also packing it in an .rpm for distros that use that packaging manager.
