### ISSUE TITLE
Android can not sign in to sync

### ISSUE THREAD

**Issue by uinguzero** [Alex313031/thorium#295]
**System Details**
 - OS: android 13
 - Thorium 117.0.5938.157

**Problem**
When trying to sign in for the sync settings, thorium says account already exists on device.
 Which it does, in the settings of my phone

**Screenshots**
![Screenshot_20231020_205800_Google Play services](https://github.com/Alex313031/thorium/assets/13848172/43d650a4-5709-4444-bff4-b5997525f9ad)

**Additional Notes**

**Comment by gz83** [comment]
https://github.com/Alex313031/Thorium-Android/issues/6

**Comment by northstarcomp** [comment]
I am getting the same Error on Android 13 from Samsung.

**Comment by radomir-mijovic** [comment]
For me the same. Did anyone found solution?

**Comment by UnnamedH** [comment]
Nope me too. Downloaded all 3 .apks for arm64 and installed them, no luck there either.

**Comment by MXKM** [comment]
Same here,too! Any solution?

**Comment by GerKersten** [comment]
Same here, Android 13, Samsung a54

**Comment by northstarcomp** [comment]
No. I think they found Google is blocking login. I think that would be anti
competitive legally. Like you have to use our browser or you can't login.

**Comment by omaralwardian** [comment]
Confirm that this is happening in Canada as well. I am unable to log in because it says that my Google account is already present on the device, which is obvious. Google must have blocked third-party access to the app. You cannot even import your passwords if you export them from Chrome. When in Thorium, going to the password manager and trying to find the button to import - it’s not there. Clearly, they took the password setting button and incorporated it into Google Play services.

Incorporate a requirement for MicroG to be present, logged in and running on devices that want to run Thorium, and it will solve the problem. MicroG acts as a proxy that provides Google with authentication with your own Google account. It doesn’t matter if you have "uncertified devices", or if you are already running GMS, or even if you are logged into other apps with GMS. I have heard in the past that people have apparently “used an app like that if they have a Huawei device without Google Play services, or could be using, I don’t know, a third- or fourth-party client for U-TOO-B /shocking" 😂

**Comment by kynadev** [comment]
Any plans to fix with microG, perhaps it could work with Vanced?

**Comment by warriorcookie** [comment]
Can confirm, same issue on Galaxy S22 Ultra

**Comment by Mak3yrM0v3** [comment]
Same problem here on One Plus Nord. Has any workaround been found?

**Comment by ShreyasJejurkar** [comment]
Even today this is happening. I'm not sure how new users are using this browser. 

Disappointed.

**Comment by marinoalfonz1** [comment]
I have an idea maybe add something like microg suuport for sign in on this browser,since google doesnt support native syncing to browser.. 

Maybe use revanced microg,which is already popular among android users..

https://github.com/ReVanced/GmsCore
