### ISSUE TITLE
f1 tv stream not working

### ISSUE THREAD

**Issue by Cromaxxx** [Alex313031/thorium#299]
**System Details**
 - OS: Win 11
 - Thorium Version 117.0.5938.157

**Problem**
f1 tv stream stuck on loading even though it works on like brave

**Screenshots**

![Screenshot 2023-10-20 231043](https://github.com/Alex313031/thorium/assets/10215299/9b3643b9-1d6d-474f-91ee-bd95c4b70f9f)

**Additional Notes**

**Comment by gz83** [comment]
I guess this website uses widevine to process audio and video

**Comment by Cromaxxx** [comment]
shame there is no fix ..great browser

**Comment by marc3lom** [comment]
Why does it work on linux and not on windows?

**Comment by Cromaxxx** [comment]
> Why does it work on linux and not on windows?

it works on linux?

**Comment by dontna** [comment]
> > Why does it work on linux and not on windows?
> 
> it works on linux?

I'm on Linux, but don't have access to the F1 TV subscription so I can't check.

However F1 TV uses **Widevine DRM** [as stated here](https://www.reddit.com/r/F1TV/comments/11uu4sg/the_state_of_f1tv_2023_march_edition/) which seems to only have a Linux patch built into the browser.

If you want to watch content from your Windows machine, instead of using Thorium you can use [RaceControl](https://github.com/robvdpol/RaceControl) which seems to have a lot of great ratings, and is OpenSource. I can't guarentee it works, so I apologise if it doesn't.

**Comment by marc3lom** [comment]
> > Why does it work on linux and not on windows?
> 
> it works on linux?

Perfectly

**Comment by gamunu** [comment]
I can confirm that it works perfectly on Linux but not on Windows and MacOS.

**Comment by gz83** [comment]
This issue has been explained in the FAQ
