### ISSUE TITLE
Check for processor using a script

### ISSUE THREAD

**Issue by oczt** [Alex313031/Thorium#31]
Firstly appreciate the work. Thanks

Could you please add a small script or info what CPUs are supported?

May be like this https://docs.01.org/clearlinux/latest/get-started/compatibility-check.html

(or it is just

`cat /proc/cpuinfo | grep avx`

**Comment by Alex313031** [comment]
@oczt Good Idea. Chromium needs SSE3 since version 90, and I noticed that just recently, the debian chromium requires the package sse3-support as a dependency, which disallows installing on unsupported processors. The maintainer of the package has sse2-support, sse3-support, and sse4.2-suuport, but no avx or avx2-support package. I contacted him to see if he can make such a package, so that Thorium and other apps requiring AVX like some data science packages on linux will refuse to install on unsupported processors.

Until such time though, I can definitely write a script to check for avx. I will distribute it with the linux releases. I'm about to make a release right now, and I will include your name in the release for credit.

Thanks for using thorium, and thanks for this issue, its something I should have considered a long time ago, considering I've gotten more than a few issues on here and the windows version with people wondering why it wasnt working for them, and they had a celeron or something which didn't support avx even though it was a haswell or skylake chip.

**Comment by Alex313031** [comment]
@oczt Here we go > https://github.com/Alex313031/Thorium/blob/main/check_avx.sh

**Comment by Alex313031** [comment]
@oczt Are you there mate? Wanna check back with you before I close this issue and make sure you saw I responded.

**Comment by oczt** [comment]
Thanks...
PS: For mere mortals' understanding, you can end the script with

Sorry... the at least a test failed, which means thorium may not run on this device.
