### ISSUE TITLE
AMD-ZEN build (AOCC)

### ISSUE THREAD

**Issue by TheRook** [Alex313031/thorium#319]
The Zen architecture contains optimizations which are not found in in the shared amd64 instruction set, the only way to compile these kinds of binaries is to use AMD's clang+llvm fork called AOCC. 

Specifically, the Zen architecture focuses on cores being able to inter-connect so the kinds of optimizations seen in the Zen architecture strongly lend themselves to heavily threaded applications like games and well... browsers:
https://www.amd.com/en/developer/zen-software-studio/applications/spack/spack-aocc.html

A very specific build of Thorium will do quite well on Zen (I don't have one). 

Using aocc with `-Ofast` AND also - this is important, it needs to have `-static` to ensure that all deps are compiled with the optimizations.  The Zen build will end up being a portable binary, which I see as an absolute win.  I noticed that maybe some security flags are disabled in Thorium?  There are some security optimizations that work well on aocc (and clang) and do not incur a measurable performance impact -  security features are an area of active development and this needs testing.

**Comment by gz83** [comment]
The more compiler parameters and optimization parameters, the better. They need to be filtered before they can be applied to compilation. The current version is compiled using Google's preconfigured llvm. The preconfigured llvm has been tested by Google and will not cause serious problems.

**Comment by TheRook** [comment]
> The more compiler parameters and optimization parameters, the better. They need to be filtered before they can be applied to compilation. The current version is compiled using Google's preconfigured llvm. The preconfigured llvm has been tested by Google and will not cause serious problems.

I agree that there is an issue of problems - that is the risk of the bleeding edge.  But I encourage you to make this build for the sake of those who choose to live dangerously.  The outcome is we chip away at the dark corners and we end up with better chips, compilers and browsers.

**Comment by gz83** [comment]
Sorry, I updated my reply

> > The more compiler parameters and optimization parameters, the better. They need to be filtered before they can be applied to compilation. The current version is compiled using Google's preconfigured llvm. The preconfigured llvm has been tested by Google and will not cause serious problems.
> 
> I agree that there could be problems - that is the risk of the bleeding edge. But I encourage you to make this build for the sake of those who choose to live dangerously. The outcome is we chip away at the dark corners and we end up with better processors, compilers and browsers.

**Comment by TheRook** [comment]
@gz83 this isn't a random assortment of optimizations - and Google won't be doing this any time soon.  

To provide more details here. `-Ofast` tells the compiler to enable every speed optimization that is approved of by the vendor. In this case by using `aocc-clang` the vendor is AMD and they set their own set of flags which are specific to Zen, there isn't any other way to tap into these features.

Now the last part `-static` means that you won't accidentally call into a library which cannot take advantage of the enhanced interconnectivity that is enabled in the Zen instruction set - it makes the entire build pure.

**Comment by gz83** [comment]
robrich might have more context on this

@Robrich999

**Comment by ms178** [comment]
Even though AOCC uses a heavily modified Clang underneath, from my experiences with such downstream forks, it is a recipe for disaster when compiling complex projects such as Thorium as there are just too many breaking bugs in there. tl,dr: Just stick to LLVM/Clang. `Ofast` might also introduce subtle bugs. 

And it is questionable if a Zen 1 build would provide any benefits over a Haswell-build. Later Zen's, maybe on newer targets. But the only worthwile experiment I can see with Zen would be Zen 4 due to AVX-512 support. But the user base is still too small for that, I guess. And for broader compatibility, x86-64-v4 might be the better choice for all AVX-512 targets in the end.

**Comment by TheRook** [comment]
Hey Alex,

Have you actually tried this build in the last 10 years or so? People don't
just leave bugs around - whatever issue you ran into 20 years ago with
-oFast isn't a problem today.  Also, if you shy away from difficult
problems, then they'll never get solved.  If you just avoid working on a
faster build, and faster compilers, then they will never improve.  Also,
you could not be more wrong about the benefits for Zen - this is
fundamentally a different chip and the compiler optimizations are wild for
some heavily-threaded operations.   But you know what is even more wild?
-Ofast works perfectly even if you have a PoS intel, and if you had a
specifically a static build with -oFast - even on a PoS intel chip - you'll
get noticeable improvements, and I bet you a case of beer it won't crash.

-Michael Brooks

**Comment by gz83** [comment]
ms178 has given some explanation on your question. In addition, this is not that we are avoiding the problem, but that the reality does not allow us to do what you said.

@TheRook

**Comment by TheRook** [comment]
@TheRook Based on your response I know didn't even try and if where to hazard a guess you are the kind of person that doesn't like being proven wrong.

**Comment by RobRich999** [comment]
Chromium is built with near ToT LLVM builds. It is done that way to address issues in the compiler side if/when incurred. Check crbug.com for clang rolls and discussions.

LLVM trunk is v18. AOCC is v16. If you want to go down that rabbit hole, expect build breakages. Want to ask me how I know? ;)

On the LTO side, ThinLTO regardless of optimization levels and LLVM passes tends to hit malloc and similar errors when trying to build certain Chromium components. AOCC is closed source, so good luck fixing the issues even if interested.

So you are looking at FullLTO instead, as in single-threaded LTO optimization and codegen. Comment out the LTO assert in concurrent_links.gni and set concurrent links accordingly in the args.gn config. That at least gets multiple LTO invokes going, but you still will hit the usual multiple-hours-long process of building the largest binaries even with a relatively modern system.

On the PGO side, you will have to generate your own profiles due to PGO versioning not being compatible. That is not my idea of fun these days. I did enough of that back in the MSVC days of Chromium.

Alternatively, one could disable LTO and PGO. That is going to put resultant Chromium builds in the performance deficit hole regardless of AOCC optimizations. Also, many of the most advanced AOCC optimizations require LTO anyway. Then there is the issue of various passes breaking during Chromium building. Get 95% into a build, and have an optimization pass crash. You can recover much of the clang build time with ccache, but you are starting over regarding LTO. o.0

Interestingly enough I kicked off an AOCC (O3, Zen2, fulllto, extra passes, etc.) build earlier today. No PGO as noted above. I have the diff patch available, though being realistic, a ToT LLVM v18 build of Chromium with LTO+PGO should be more performant; probably by a considerable margin.

Likewise, based upon personal experience, expect about the same with Intel ICX based upon LLVM v17.

Whatever compiler is used, -Ofast is not a good idea with Chromium. Been there, done that. I can get a build accomplished with -Ofast or -ffast-math. Previous attempts have even run, right along with numerous crashes. I have even narrowed down fast-math to select components in the hot paths, and the results tend to be the same. There is plenty of FPU/SIMD code in Chromium and third_party components that does not respond well to fast-math.

----------------

BTW, I pushed a Zen 2 test build for Linux yesterday. My primary notebook has an AMD 5700u proc.

https://github.com/RobRich999/Chromium_Experimental/releases/tag/v120.0.6096.0-r1216665-linux64-deb-avx2-znver2
