### ISSUE TITLE
API Keys for personal build

### ISSUE THREAD

**Issue by jessy-lua** [Alex313031/Thorium#33]
I build Thorium from sources, set the: 
google_api_key
google_default_client_id
google_default_client_secret

In google console I see only safebrowsing API request, but on "Chrome Sync API" zero requests and sync not working.

**Comment by Alex313031** [comment]
@jessy-lua You made your own API Keys?

**Comment by Alex313031** [comment]
@jessy-lua When using Thorium releases, or your own with your own api keys, you have to add yourself to this group > https://groups.google.com/u/1/a/chromium.org/g/google-browser-signin-testaccounts  as per > https://www.chromium.org/developers/how-tos/api-keys/#signing-in-to-chromium-is-restricted because google decided to be a numbnuts on mar. 15, 2021.

If you need help making API Keys with all the required APIs, or if you would like access to the ones Thorium uses (NOT for redistribution) lemme know.

**Comment by jessy-lua** [comment]
> @jessy-lua You made your own API Keys?

yes



> @jessy-lua When using Thorium releases, or your own with your own api keys, you have to add yourself to this group > https://groups.google.com/u/1/a/chromium.org/g/google-browser-signin-testaccounts as per > https://www.chromium.org/developers/how-tos/api-keys/#signing-in-to-chromium-is-restricted because google decided to be a numbnuts on mar. 15, 2021.
> 
> If you need help making API Keys with all the required APIs, or if you would like access to the ones Thorium uses (NOT for redistribution) lemme know.

ofcourse i read this before and joined group and created api keys and added all needed libraries

**Comment by Alex313031** [comment]
@jessy-lua If you did it all right IDK why it wouldn't be working for you. Would you like access to my private API keys repo to test to see if those work? Keep in mind as per the readme in that repo that it is NOT for redistribution, I.E. keep them to yourself only for a personal build. I don't want a whole bunch of people all of a sudden using them because then it might reach my quota and then they wont work for anyone.
