### ISSUE TITLE
The app does not open

### ISSUE THREAD

**Issue by Ab-Mr** [Alex313031/thorium#353]
**System Details**

 App version; Thorium Version M117.0.5938.157 - 53rd Release

Name OS; Fedora Linux 38 (Workstation Edition)
Windowing system; Wayland
Kernel version ; Linux 6.5.7-200.fc38.x86_64
GNOME version; 44.5

**Problem**

> A clear and concise description of what the bug is.
[33818:33818:1026/140130.657980:ERROR:policy_logger.cc(154)] :components/enterprise/browser/controller/chrome_browser_cloud_management_controller.cc(163) Cloud management controller initialization aborted as CBCM is not enabled.

> [1026/140131.599139:ERROR:elf_dynamic_array_reader.h(64)] tag not found
>

> [1026/140131.601355:ERROR:elf_dynamic_array_reader.h(64)] tag not found
> 

> zsh: illegal hardware instruction (core dumped)  thorium-browser

**Screenshots**

**Additional Notes**
The app does not open

**Comment by Hamza12700** [comment]
Have you changed any policy related to Chromium or Chrome in general cause it seems like the error `[33818:33818:1026/140130.657980:ERROR:policy_logger.cc(154)]` references a specific file and line number in the Thorium Browser source code. Maybe the issue is related to the browser policy.

`Cloud management controller initialization aborted as CBCM is not enabled`:
This part indicates that the initialization of the Cloud Management Controller was aborted because CBCM (Chrome Browser Cloud Management) is not enabled. It might be related to cloud management policies or some settings in the browser.

`[1026/140131.599139:ERROR:elf_dynamic_array_reader.h(64)] tag not found` and `[1026/140131.601355:ERROR:elf_dynamic_array_reader.h(64)] tag not found`: These lines are indicating errors related to related dynamic array tags. Maybe try to reinstall the browser.

Finally the last error: `zsh: illegal hardware instruction (core dumped) thorium-browser` indicates that there is an incompatibility, an issue with the browser's build or problems with your hardware.

**Comment by dibash-sapkota** [comment]
Same error with following message on linux mint

[18667:18667:1027/082705.332984:ERROR:policy_logger.cc(154)] :components/enterprise/browser/controller/chrome_browser_cloud_management_controller.cc(163) Cloud management controller initialization aborted as CBCM is not enabled.
[1027/082707.034461:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1027/082707.038748:ERROR:elf_dynamic_array_reader.h(64)] tag not found
Illegal instruction (core dumped)

**Comment by gz83** [comment]
please use this version

https://github.com/Alex313031/Thorium-SSE3/releases/tag/M117.0.5938.157

@Ab-Mr @dibash-sapkota

**Comment by Ab-Mr** [comment]
I don't think so. I didn't install Chrome in the first place. But thanks for the information.

@Hamza12700

**Comment by Ab-Mr** [comment]
Thanks, @gz83

**Comment by debianuser160** [comment]
My app doesnt open

App version: Thorium M117.0.5938.157
OS: Linux debian 12(bookworm)
kernel version: 6.1.0-12-amd64 (64-bit)
KDE Plasma version: 5.27.5

**Comment by gz83** [comment]
> My app doesnt open
> 
> Please help
> 
> App version: Thorium M117.0.5938.157 OS: Linux debian 12(bookworm) kernel version: 6.1.0-12-amd64 (64-bit) KDE Plasma version: 5.27.5

It may be that the CPU is too old and cannot use the AVX and AVX2 instruction set versions. You can download and install the SSE3 version from the Thorium-SSE3 repo.

@debianuser160

**Comment by debianuser160** [comment]
ok thx
