### ISSUE TITLE
Change macOS icon

### ISSUE THREAD

**Issue by ivangoldov** [Alex313031/Thorium#40]
Hello, firstly, great browser! 

I'd like you to change the Thorium browser icon to match macOS 11+ style. This is google chrome icon which matches style (square with rounded corners and an icon inside it). 
![image](https://user-images.githubusercontent.com/47887209/172161650-b5b6cd5e-778b-4bb6-94c8-e0daa9750bcf.png)
I know that changing icon in macOS is easy and everybody can do it, but couldn't it be better if it was authentic by default?

**Comment by Alex313031** [comment]
@ivangoldov The reason Thorium is using the plain icon, is because I couldn't get ahold of a high enough resolution version of the mac icon. The Thorium icon for all platforms was made from an official Chromium .SVG that I manually edited in a text editor to have the black inner ring instead of white, rendered at 16384 x 16384, and then downscaled to all the various sizes needed in the source code. I asked for Windows and Mac icons. (Windows actually has a subtle gradiant across the colours, but I couldn't get a high enough resolution for that either. But it's hardly noticable on windows.) You can see where I tried to get this at  > https://github.com/alrra/browser-logos/issues/206#issuecomment-1045681314 and https://github.com/alrra/browser-logos/issues/206#issuecomment-1047971703 

Here's what the Mac Icon would look like if I used those.
![155174629-d5043180-ab84-4cd8-b68a-27bb8c6d1049](https://user-images.githubusercontent.com/45863095/172295318-fe1f0206-9102-49ca-99c4-f12321e46b38.png)

**Comment by Alex313031** [comment]
@ivangoldov I might try to make my own, by getting an .svg of a blank "MacOS Icon", and overlaying the Thorium .svg on it.

**Comment by Alex313031** [comment]
@ivangoldov I made a new icon. I upscaled the chromium one from 1024 x 1024 to 2048 x 2048, and then used the paint bucket to white it all out, then I overlayed the thorium.svg @ 1600 x 1600px, and exported it. The result it this 2048px icon. What do you think?
![Thoriummac](https://user-images.githubusercontent.com/45863095/172297438-19392860-8cee-49a9-8446-37927928d4e3.png)

**Comment by Alex313031** [comment]
@ivangoldov Also did basically the same thing with the document icon.
![document_1024](https://user-images.githubusercontent.com/45863095/172300487-9c703ede-801c-459a-ac06-867ad66a426d.png)

**Comment by Alex313031** [comment]
@ivangoldov Uploaded the new icons and made a new dir for generating the required .icns files for MacOS builds.
https://github.com/Alex313031/Thorium/tree/main/logos/NEW/mac/gen#readme

**Comment by ivangoldov** [comment]
@Alex313031 I like new icons, thank you very much!
