### ISSUE TITLE
Review and my response to defend Thorium

### ISSUE THREAD

**Issue by trimechee** [Alex313031/thorium#411]
Hello, there is a video from a youtuber who said he sent you an email....he talked about the positive points of our beloved Thorium Browser but he made criticisms that I find severe, I am not posting it video but I commented on it and I also post: we comment here and I think Mr Alex you must respond to him because you do a wonderful job and we must not let people criticize this wonderful Thorium project, to update it, I think to silence the criticism, optionally include an updater in the installer even if some prefer to do a manual update to save resources:

"Even if you tried to be balanced, I find your criticisms a little too harsh, for example concerning ublock origin installed by default, the developer of ublock origin has developed new version ublock lite which works well because I test it and which uses the manifest v3 and which does not consume cpu, and then why judge Thorium on a possible future, perhaps google will no longer implement the v3 manifest?

already ublock origIN is a bonus, a gift, and Thorium brings AVX2 and hardware acceleration support for close source codecs while other major famous browsers do not have adequate harware acceleration support for certain not open source codes, for update, I don't like the updaters in the backend and in the task scheduler which can consume resources and those who install Thorium have technical skills and can check new updates, and there is even an updater for Thorium browser. ....for the chromium version, new versions can bring bugs so it is better to stay on more stable versions and Thorium makes a new version every month, it is very difficult 6 hours of intensive use of the computer to make new version, we use Thorium for dark mode, hardware gpu support for cloe source codecs....this is why we like Thorium which has new exclusive new functions, I suggest you to make new version for balance to palpate new new features that Thorium Browser has compared to other browsers, and other famous browsers with ad blocking let certain ads through, it is proven but Throium blocks all ads and does not do deals for let ads pass"

**Comment by proxer05** [comment]
You refering to [Brodie Robertson](https://www.youtube.com/@BrodieRobertson) video right? Why are you hiding this? Imho he did healthy criticisms. You making criticizm look like something bad but is it?
> chromium version, new versions can bring bugs so it is better to stay on more stable versions 
Nobody said to make thorium based on bleeding edge version. Problem is that browser have to be up to date and im talking about chromium subversion(patches should work without additional work) as browser CVE's are dangerous and sometime hard to avoid. At current scale of project i dont think CI weekly/biweekly builds are possible as standard quotas arent enough for building chromium but at some point it should be a thing imo.
>it is very difficult 6 hours of intensive use of the computer to make new version
Thats truth. Maintaining browser by (mostly)yourself isnt easy task. And Brodie pointed one solution for this problem - working at Thorium under github organization.
Watch it again and take a cold look at this video.

**Comment by proxer05** [comment]
Damn chill. He and I just gave an opinion on some points of your project. Me at least doesn't demand you to change how you maintain thorium. Is it bad to publicly tell you what you don't like? 
Anyway I would like to say sorry to you as my words misled my idea(as criticism doesn't equal speech of hate). I really appreciate keeping this project alive as I actively use it on one of my devices and it works great.

**Comment by trimechee** [comment]
@proxer05 Lol really  do you think I'm Alex ? I'm a literary person, I know almost nothing about programming haha, please  read my discussions with Mr Alex and you will know I don't know anything about software development lol, I'm just a grateful user who defends Thorium and that's the least I can do,  @Alex313031 @gz83 confirm that I'm not Mr Alex hahhaha

**Comment by trimechee** [comment]
@proxer05 oups i forget my profile was private, now i make my profile public, you can read my discussions with Mr Alex @Alex313031 and you will know i am not Mr Alex because i don't know anything about how developing program lol, yes i study pascal in school, some times i have good marks in exam about microsoft word hhhhh but in programming languages, I got average grades....

**Comment by trimechee** [comment]
@proxer05 I am an Arab, I am not American, I can give you my Twitter account where I write in French because a lot of French people are Arabs and I have a lot of Arab subscribers from France and also I write in Arabic Sometimes in my twitter....

**Comment by trimechee** [comment]
@proxer05 Mr Alex doesn't have time to deal with reviews, he has softwares to develop, here is proof among a lot of proof that I am not Mr Alex lol, I asked Mr Alex to implement these features and he told me that he is not going to implement them.....

https://github.com/Alex313031/quark-player/issues/12

**Comment by trimechee** [comment]
> Damn chill. He and I just gave an opinion on some points of your project. Me at least doesn't demand you to change how you maintain thorium. Is it bad to publicly tell you what you don't like? Anyway I would like to say sorry to you as my words misled my idea(as criticism doesn't equal speech of hate). I really appreciate keeping this project alive as I actively use it on one of my devices and it works great.

@proxer05 thank Mr Alex not me, I know nothing about software development, it is absurd to believe that Mr Alex made a fake account to defend his software! he can defend without software without a fake account and it is a lack of respect that you can think that I am Mr Alex, I invite you to present your most sincere apologies to Mr Alex @Alex313031

**Comment by trimechee** [comment]
@proxer05 Mr @gz83 can confirm you that i am not Mr Alex, it will be good te delete your post and apologize, thank you

**Comment by itsHanibee** [comment]
This issue is completely unwarranted for. As much as I love Thorium, Brodie had very good points that he brought up. Obviously maintaining a project that's as huge as a browser is a massive endeavour on a single person. You can't always match with upstream's pace and you can't always make sure merges happen fine without any conflicts, But then again we saw multiple extremely good projects die because the project's popularity exceeded the author's original estimations. Being prepared for it is not bad at all especially if it doesn't have any downsides.

Instead of completely shunning what people have to say it's best to atleast listen and gather insight as to where you're falling behind.
Thorium is still a very new project all things considered. And who knows, Alex might've planned for everything Brodie mentioned already like the Updater and moving to an organisation and bringing on more contributors at a later date. You don't know.

**Comment by gz83** [comment]
The Thorium project is open source and has not restricted anyone's speech since its inception. However, it should be noted that all discussions must comply with the laws and regulations of the country or region in which they are located (users come from all over the world), Thorium's code of conduct, and Google's code of conduct.

On the basis of the previous things, we accept praise or criticism and will consider them carefully.

Any product has advantages and disadvantages, and Thorium does the same. After watching Brodie’s video, I summarized the following points (my native language is not English, so I may have missed it or my understanding is biased):

1.Thorium's icon (including logo and icon on omnibox)
2.Thorium's help documentation
3.Improve DNT (do not track) mechanism
4.random fingerprint
5.ungoogled or reduce tracking
6.Store installation packages on more package managers and automatically update them when conditions permit
7.Bring in more contributors
8.Follow up the release of stable versions as much as possible
9.Consider the impact of MV2 and MV3 on browsers

These suggestions sound good to me, and some of them are things I've always wanted to implement, but we have to respect Alex's opinion as to whether they can be brought into Thorium.

In addition, if anyone wants to contribute to Thorium, you are welcome to submit a PR at any time, and Alex, myself and others will review it.

**Comment by 3k2** [comment]
[Thorium Browser | Is it the best browser?](https://youtu.be/d1c3Y42Bt7s)

[The Fastest Browser in the World?](https://youtu.be/yz5rs_1pEAA)

here are the videos I have watched myself. It seems to me at least since there isn't many people contributing to the project it self Mercury browser is getting way less attention from the devs. Perhaps it's time to choose which one get's your full attention and which one doesn't?

**Comment by itsHanibee** [comment]
is it possible to close this?, a discussion like this doesn't belong here in github issues I feel like.
