### ISSUE TITLE
Couple things with 105.0.5167.0

### ISSUE THREAD

**Issue by raisedintheusa** [Alex313031/Thorium#44]
With the last release, my system sees Thorium as "thorium-browser-unstable" even though I'm executing the "thorium-browser" script. Not sure if this is on purpose or not. With the past couple releases, my system would see it as just "thorium-browser".

And this might be nitpicking a little, but the flag "--disable-features=EventPath" is passed twice, once before "--flag-switches-begin" and another time after.

**Comment by Alex313031** [comment]
@wdym it "sees" it as thorium-browser-unstable? Could you post a screenshot(s) of everything you are describing?

And the eventpath thing is an upstream chromium thing.

**Comment by raisedintheusa** [comment]
I use the mouse gesture program Easystroke and it would recognize the last few versions as "thorium-browser" so the same gestures would work on a new release, but with the last release the gestures stopped working and when selecting Thorium again within Easystroke, I saw it now recognized it as "thorium-browser-unstable".

**Comment by ms178** [comment]
@Alex313031 

Some observations with this build from me. First of all thanks a lot for getting Google Sync working, I now can use Thorium as my new default browser. 

On the other hand, I faced some trouble with the user-provided PKGBUILD for Arch Linux as that does no longer work with this release out-of-the box. 

There are several reasons, the first is due to the different package name in the source section which points to the released DEB-file on Github, a consistent naming scheme over all releases would fix that. While that was easy to fix in the PKGBUILD, this is also avoidable. 

For reference, the first entry is the command used for the new version, the one after the comment symbol was the one used before.

```
source_x86_64=("https://github.com/Alex313031/Thorium/releases/download/M${pkgver}/thorium-browser_${pkgver}_amd64.deb"
#"https://github.com/Alex313031/Thorium/releases/download/M${pkgver}/thorium-browser_${pkgver}-${pkgrel}_amd64.deb"
)
```

I am a bit puzzled about the other two problems, as I also had to comment out the following lines:

`#chmod 4755 "$pkgdir/opt/chromium.org/thorium-unstable/chrome-sandbox"`

and the whole install icons section 

```
# install icons
    #for i in 16x16 24x24 32x32 48x48 64x64 128x128 256x256; do
    #    install -Dm644 "${pkgdir}"/opt/chromium.org/thorium-unstable/product_logo_${i/x*}.png \
    #                   "${pkgdir}"/usr/share/icons/hicolor/${i}/apps/thorium-browser-unstable.png
    #done
```
I don't know if they are no longer needed or if my solution was just a dirty hack to get the new package to install, but for anyone interested, here is the now working PKGBUILD:
[PKGBUILD.txt](https://github.com/Alex313031/Thorium/files/9086461/PKGBUILD.txt)

**Comment by ms178** [comment]
As the icons went missing this way, and I noticed that the directory name has changed as well, hence some adjustements to the file path in the PKGBUILD were needed to get it working, here is the now fixed 
[PKGBUILD.txt](https://github.com/Alex313031/Thorium/files/9087572/PKGBUILD.txt)
.

**Comment by Alex313031** [comment]
@raisedintheusa This should fix your initial issue https://github.com/Alex313031/Thorium/commit/947c28a91dbab41e4931747389a19fb1db717279

**Comment by raisedintheusa** [comment]
Issue fixed with release 38.
