### ISSUE TITLE
Enable support to select custom search engines & add them to thorium.

### ISSUE THREAD

**Issue by The-Maize** [Alex313031/thorium#444]
**Is your feature request related to a problem? Please describe.**
with linux version i have been unable to select my prefered search engine. its not in the default list, and i am not able to add it manually. 

The default list doesnt contain a lot of privacy respecting search engine choices except duckduckgo. while that is ok, its not the best. 

**Describe the solution you'd like, including relevant patches or source**
I would like to see support to add our own choices of search engines. or at least have a larger more complete lists of available search engines, including some of the not so mainstream choices, like startpage.

**Additional Notes**
would also like to see them potential enable disable, rather than delete permanently as well so they can be reinstated with out a reinstall.

**Comment by midzer** [comment]
Adding a custom search engine is already possible in Chrom* based browsers.

Your search engine is your friend on how to do it.

**Comment by EmperorEndru** [comment]
I'm aware this is a dated thread, but on Windows release name "**M119.0.6045.214**", I ran into the same, or similar issue.
Attempting to add a custom search engine site via "**Add**" button, I was unable to set the site as the default search engine due to the option being greyed out in the drop-down menu for all entries.

However, there is a way around this. Extensions. If the Chrome Web Store has an extension for the search engine you wish to add and use by default, it is possible to use said extension for this purpose. 
The example presented, Startpage, is one such search engine.

The issue presented appears to be more of a user friendliness, or interface issue. Keep in mind that this is coming from the user end, and this information is presented without knowledge of where the files are on the system that store the search engine information.

Hope this helps. Happy browsing.
