### ISSUE TITLE
UNable to remove Google Hangouts from Extensions

### ISSUE THREAD

**Issue by Astr0wars** [Alex313031/thorium#449]
**System Details**
 - OS: Ubuntu 22.04
 - Thorium Version Version 117.0.5938.157 (Official Build) stable
**Problem**
In extensions Google Hangouts is unable to be disabled or removed. This is not the case in Chrome, so reporting this as a bug.

**Screenshots**

![Screenshot from 2023-11-24 05-18-16](https://github.com/Alex313031/thorium/assets/108596107/5c0ce1b3-a0be-44e9-9d18-3843d56a66bc)

**Additional Notes**

I looked on Chrome and the Hangouts extensions isnt installed by default. Sidenote: I'd also like to [at least have the option] to remove the Chromium PDF viewing extension, I have a program for that.

**Comment by peterlerche** [comment]
Me too

**Comment by ags1234** [comment]
I would also like to remove Hangouts. Even better, Thorium should come without it.

**Comment by Tre-brock** [comment]
Yeah idk why this is here along with the other unremovable exention, like it could be avuble to download but it doesn't make sence to come preinstalled and not removable.

**Comment by mezhgano** [comment]
So how to remove this unwanted shit with such a dangerous permissions?

**Comment by SilentWarrior1** [comment]
so... any news how to remove them?

**Comment by gz83** [comment]
This is a built-in extension of the browser and is not allowed to be deleted for the time being. We are just taking some measures to display them all.

**Comment by Templayer** [comment]
![image](https://github.com/Alex313031/thorium/assets/11728067/e1269f57-f794-4a5b-abf7-e4870c6a515f)

And it is forcefully enabled in incognito. You have some explaining to do.

**Comment by Alex313031** [comment]
@mezhgano @Templayer @SilentWarrior1 @ags1234 *Every* Chromium based browser has these extensions built in. Since they are built in and not removable, they are normally hidden. I just take a patch from Ungoogled Chromium to display *ALL* extensions, no matter the state.

This can be seen in Ungoogled Chromium too.

Also, you can make these appear in Brave, regular Chromium, or Google Chrome, by appending the commandline switch `--show-component-extension-options` (The patch mentioned above simply always enables the toggle that this commandline flag normally controls).

There are three. Specifically what they do are:

"Chromium PDF Reader" - Used for embedding PDFium when viewing PDFs. Removing this would cause all PDFs to stop displaying.

"Google Hangouts" - Added when using the build arg `enable_hangout_services_extension = true`. This enabled proper Audio/Video passthrough when using Google Hangouts. It is never activated unless you are using that site.

"Web Store" - Under the 'Chrome Apps' section. This is self explanatory and provides integration with the Web Store to treat it as a special domain that doesn't allow extensions scripts to run on it, and to allow .crx files to be installed (to install extensions from the store), rather than just downloading them like a normal file.

So, these extensions are harmless, normal, and would break functionality if they are removed.

**Comment by Templayer** [comment]
> "Chromium PDF Reader" - Used for embedding PDFium when viewing PDFs. Removing this would cause all PDFs to stop displaying.
> 
> "Google Hangouts" - Added when using the build arg enable_hangout_services_extension = true. This enables proper Audio/Video passthrough when using Google Hangouts. It is never activated unless you are using that site.

I'm not using the functionality of these two. Screw hangouts, and I'm using Foxit Reader to show PDFs.

Is there really no way of pragmatically disabling these, or at least to disable them in Incognito mode?

**Comment by Alex313031** [comment]
@Templayer the PDF reader will not be disabled. It has to be disabled at the source level. Most people use the built in PDF reader, so I'm not going to disable it because that would break functionality for alot of people including me.

Why are you so concerned about hangouts? Like I said it only activates when you use the hangouts site, and even then, its not like it sends out any information. It's just used as a bridge to allow special permissions regarding microphone, etc.

**Comment by Templayer** [comment]
> Like I said it only activates when you use the hangouts site, and even then, its not like it sends out any information. It's just used as a bridge to allow special permissions regarding microphone, etc.

And if somebody finds a weakpoint and spoofs the website?

**Comment by Alex313031** [comment]
@Templayer IDK, like I said almost every other Chromium based browser has this extension, and I haven't heard of any security vulnerabilities ever happening related to it.

**Comment by javierriveracastro** [comment]
Well, at the end that extension is designed to leak CPU info to any google.com website. 

Cab you remove it now?

**Comment by Alex313031** [comment]
@javierriveracastro @Templayer Following more research and complaints, I have removed it from Thorium since M124, so I am closing this now.
