### ISSUE TITLE
Removing Google telemetry/Spying

### ISSUE THREAD

**Issue by Tre-brock** [Alex313031/thorium#454]
I don't need Google services like docs and sync to be removed. I would just like if you could make the browser not send all my browsing data to google. Like have a toggle to use sync and those other things.
You could look at ungoogled chromium to get an idea of what to do, but if you could remove google spying would be great and would make this the number one browser, but for now this is preventing me from using it because I care about my privacy.
This would be kinda how in the mercury browser where you removed all of this stuff.

**Comment by mutageneral** [comment]
Same for me here. Maybe have a different build based off of ungoogled-chromium so that you can choose?

**Comment by xathian** [comment]
I think you misunderstand the entire point of Thorium. It's not meant to be a privacy freak browser, it's very intentionally keeping google integration for people that want optimizations of things like ungoogled chromium but keeping the integrations of chrome

**Comment by rubyFeedback** [comment]
"but keeping the integrations of chrome"

I kind of use thorium for the promised speed focus. I don't really use it to want to use Google services - in fact
I want to move away from ALL Google products, including google search (I may even downgrade myself to
duckduckgo, as the google search results are consistently awful in the last 2 years; youtube search also sucks,
they just show random videos that have nothing to do with my search result).

My point is that use cases of people vary, so the original's author request is, in my opinion, perfectly
valid. Just because OTHER people have a different use case does not invalidate the original opinion.
The proper way to resolve something, then, is to make it an easy option for people to switch stuff.
Then people can **decide on their own**, rather than have some random person on the internet decide
for them.

**Comment by Commandcracker** [comment]
Heaving a separate build for Thorium (ungoogled-thorium) would probably be the best solution. I personally don't want to give google my data with open arms, but some people "just want a faster Chrome". They want to keep using all features Chrome provides (Google services).

I'm a "hardcore" Firefox user, and the only thing that keeps me away from Thorium is that it ships with Google Services. (It may also be nice to have some security features like User agent spoofing/switching or canvas blocking build into the browser.)

**Comment by trytip** [comment]
open about:about in firefox, click about:config and search for Google.  firefox aslo has google embedded in the code.  you can spoil all these google strings, i usually just edit blank it out.

**Comment by c33s** [comment]
crosspost from thorium-legacy, i am also looking for an ungoogled version https://github.com/Alex313031/thorium-legacy/issues/106

in short: 

request for an ungoogled version
-  for legacy as it is the only option for <win10
-  for all as an ip is PII and should never be exposed to google servers

**Comment by gz83** [comment]
https://github.com/Alex313031/thorium/blob/main/docs/FAQ.md
