### ISSUE TITLE
"Show in Folder" crashes with 105.0.5183.0

### ISSUE THREAD

**Issue by ms178** [Alex313031/Thorium#48]
- good: ca. 4% better performance in WebGL Aquarium, from 94 to 98 fps

- bad: the app crashes reproducibly if I download a file and click on "Show in folder" option in the context menu to browse the directory where I downloaded the file; see the attached screenshot below

![Screenshot_20220719_130559](https://user-images.githubusercontent.com/19559105/179736204-18b70f41-484a-4fee-8a37-13036206d2f0.png)

If I click on "Show in folder" [= In Ordner anzeigen in German], the app immediatly force closes.

**Comment by raisedintheusa** [comment]
Yes, I have the "Show in folder" crash too.

**Comment by raisedintheusa** [comment]
Also, this might just be a personal preference, but I'm not the biggest fan of the "Thorium blue" that colors some items in the browser. It seems a little hard on the eyes against a dark theme. Especially now that the tab volume speaker favicon is also taking on that blue, but the little volume bars beside it still being white, it isn't a good look.
Also, the right-side menu button looks like I'm looking at the previous design just with my eyes crossed.

**Comment by Alex313031** [comment]
@raisedintheusa @ms178 Yes, I'm experiencing the download show in folder crash too. Next release should fix it.
The volume bars color is fixed, it was an error on my part editing the .icon file. Next release will fix that.
I have experimented around with different colors, I might change it in the future.

The main menu or hamburger icon is actually from brave. I always liked the lines rather than dots, and this was actually the default for chromium until version 55. You can actually see where I noted the source of it from braves repos here.https://github.com/Alex313031/Thorium/blob/main/src/chrome/app/vector_icons/browser_tools.icon#L5

As far as the coloring, I would like it to be blue. The only issue is whether to use #1967D2 or #1A73E8. When using the former, it looks too dark in normal mode, but good in dark mode. When using the latter (what the icons are colored as now), it looks good in normal mode, but too light in dark mode. While I use dark mode myself, as well as adding patches to add a chrome://flag for it and a right click option for the .desktop file, more people are going to use it as is (in normal/light mode), so I made the decision to go with #1A73E8. I also chose this because this is the color used for the extension favicon on chrome://extensions, as well as for blue colors in WebUI internal pages. I might change it to something else like I said, but it must be a relatively neutral color that looks good in both dark and light mode.

Also, the reload button is getting recolored, and I am removing the blue color from the back and forward buttons, since they dont dim when there is not a page to go forward or back to like they should.

**Comment by Alex313031** [comment]
@ms178 It is fixed.
