### ISSUE TITLE
Failed to create WebGPU Context Provider

### ISSUE THREAD

**Issue by OttCS** [Alex313031/thorium#535]
**System Details**
 - OS: Nobara 39 (Fedora 39 base)
 - GTX 1660 Ti + proprietary driver version 535.154.05
 - Thorium Version 120.0.6099.235

**Problem**
WebGPU seems to not have support, even after tweaking chrome://flags and launching from the terminal with arguments. Site I'm using: https://thebeautifulones.pages.dev/adopting-webgpu

Without Chrome flags:
Console warning "Failed to create WebGPU Context Provider" and the site defaults to using WebGL.

With Chrome Flag enable-unsafe-gpu (with or without --enable-features=SkiaGraphite and flag skia-graphite flag):
Console warning "WebGPU on Linux requires GLES compat, or command-line flag --enable-features=Vulkan, or command-line flag --enable-features=SkiaGraphite (and skia_use_dawn = true GN arg)"

With argument --enable-features=Vulkan:
Terminal repeats: ERROR:vulkan_swap_chain.cc(409)] Swapchain is suboptimal.

**Additional Notes**
- https://toji.github.io/webgpu-test/ does not work either.
- WebGPU is wacky and isn't a completely implemented standard, and the same issue persists with Google Chrome for my system. WebGPU is being enabled by default in chromium browsers like Chrome, Edge, and Opera (https://caniuse.com/webgpu), and Thorium supporting this by default would be great for less savvy users who don't want to tweak flags or launch Thorium from the terminal with arguments.

**Comment by Alex313031** [comment]
@OttCS WebGPU on Linux requires not only the flag chrome://flags/#enable-unsafe-webgpu , but also Vulkan to be enabled as the backend chrome://flags/#enable-vulkan Since this is not a supported configuration, and is known to break things and/or cause graphical artifacts, I won't enable this by default. Sorry. I love WebGPU too and I wish they would speed up porting it to OpenGL on linux. I actually have a WebGPU test page on the site that is a slightly modified version of an upstream one. See > https://thorium.rocks/misc/webgpu-test/

**Comment by OttCS** [comment]
I didn't know there was a built-in flag for it, cool! Bugs do take priority, I'll close the issue and hope that eventually Linux gets WebGPU. Thanks for the quick response!
