### ISSUE TITLE
Debian Repo is down

### ISSUE THREAD

**Issue by ravarage** [Alex313031/thorium#567]
https://dl.thorium.rocks/debian/
is down

**Comment by gz83** [comment]
@midzer

**Comment by midzer** [comment]
We switched to `HTTP`

http://dl.thorium.rocks/debian/

**Comment by ravarage** [comment]
oh, sorry but it missing latest 121 update, as its not issue I will close it thank you

**Comment by midzer** [comment]
Gonna update the debian repo soon.

**Comment by phoenix-oes** [comment]
> E: The repository 'http://dl.thorium.rocks/debian stable Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by midzer** [comment]
@phoenix-oes Yes, it is not gpg signed.

Content of `thorium.list`:
```
deb [trusted=yes arch=amd64] http://dl.thorium.rocks/debian/ stable main
```

If anybody gives me a direction on how to do it, it would be appreciated.

**Comment by phoenix-oes** [comment]
> If anybody gives me a direction on how to do it, it would be appreciated.

### REPOSITORY CONFIGURATION

If you want to provide archive signatures in an archive under your maintenance you have to:

* _Create a toplevel Release file_, if it does not exist already. You can do this by running `apt-ftparchive release` (provided in apt-utils).
* _Sign it_. You can do this by running `gpg --clearsign -o InRelease Release` and `gpg -abs -o Release.gpg Release`.
* _Publish the key fingerprint_, so that your users will know what key they need to import in order to authenticate the files in the archive.
  - It is best to ship your key in its own keyring package like Ubuntu does with ubuntu-keyring to be able to distribute updates and key transitions automatically later.
* _Provide instructions on how to add your archive and key_. If your users can't acquire your key securely the chain of trust described above is broken. How you can help users add your key depends on your archive and target audience ranging from having your keyring package included in another archive users already have configured (like the default repositories of their distribution) to leveraging the web of trust.
  - Whenever the contents of the archive change (new packages are added or removed) the archive maintainer has to follow the first two steps outlined above.

(from "man apt-secure")

More information:

1. Debian Security Infrastructure
    - https://tldp.org/LDP/www.debian.org/doc/manuals/securing-debian-howto/ch7.en.html
2. Strong Distribution HOWTO
    - https://www.cryptnet.net/fdp/crypto/strong_distro.html

**Comment by midzer** [comment]
Thanks for contribution @phoenix-oes 

We are going to discuss this with Thorium team.

**Comment by proofy** [comment]
Why did you switch off https?

**Comment by midzer** [comment]
@proofy We migrated Thorium debian repo to a new machine.

Reason for not re-enabling HTTPS:

* Download performance
