### ISSUE TITLE
HRR fix for tabstrip animations

### ISSUE THREAD

**Issue by ChameleonCiskoCZ** [Alex313031/thorium#574]
**Is your feature request related to a problem? Please describe.**
When you close tab, then while the tabs are moving and resizing, the animation is always 60hz, not adjusted to high refresh rate monitors.

**Describe the solution you'd like, including relevant patches or source**
https://danglingpointer.fun/2022/09/06/FasterChromium/
The issue is pretty well documented on this website, better than i could do here.

**Comment by gz83** [comment]
The articles you provide may contain outdated content.  In addition, high refresh rates should not be pursued blindly, and I tend not to modify the behavior involved.

**Comment by ChameleonCiskoCZ** [comment]
I posted the article because it should lead to relevant code that is causing this issue that is still present, for years. This is one of main reasons i tend to use firefox, because on my 165hz monitor, tabs are terribly laggy.

https://issues.chromium.org/issues/40567978 There is also this chromium issue open that should be related to this bug, if it helps.

**Comment by gz83** [comment]
Thanks for the information, I also use a 165 Hz refresh rate monitor and I don't feel any lag, but I can understand that because these perceptions vary from person to person.

Also, I've confirmed that parts of the article are out of date, and we may consider adjusting the framerate that's hardcoded in the code, but the final decision will be made by Alex.
