### ISSUE TITLE
DuckDuckGo New Tab Page

### ISSUE THREAD

**Issue by HappyLoLTroll** [Alex313031/thorium#576]
**System Details**
 - OS: Windows 11
 - Thorium Version 121.0.6167.204

**Problem**
Hi, in Chromium, when I set DuckDuckGo as the default search engine, it overrides my New Tab Page to this:
![chrome_l2cGAxttss](https://github.com/Alex313031/thorium/assets/71263735/e0824913-b220-4fdb-a17e-abedb8f73bcf)

But in Thorium the page doesn't change to the duckduckgo one, and remains the "blank" new tab page:
![image](https://github.com/Alex313031/thorium/assets/71263735/19ee21b0-92c1-41a3-ba8c-73af65ce47a5)

I wanted to know if it is possible to change that page to the duckduckgo one.

**Comment by Quisquose** [comment]
It's not just DuckDuckGo though; it's **ALL** search engines other than Google. 

In Thorium they all show blank pages, and none of them offer any customisation either. 

You can't even prevent previously visited sites from being displayed on the page. Instead you have to keep deleting site icons one-by-one whenever they appear (and they just keep coming back each time you visit a site).

It is definitely a Thorium issue because Supermium does _not_ have this problem. Supermium displays all search engines correctly (see example screenshots below).
 
 
![Clipboard  27  07 31 03](https://github.com/Alex313031/thorium/assets/7541455/12fc5fb5-8884-4552-abad-da6e17cffdcc)
 
 
![Screenshot 2024-06-01 (01)](https://github.com/Alex313031/thorium/assets/7541455/dfd678bf-6edd-4eda-8edc-382c7d53dd88)
  
 
![Screenshot 2024-06-01 (03)](https://github.com/Alex313031/thorium/assets/7541455/98da9773-9727-4d3a-9763-9c11fe9450e7)

**Comment by HappyLoLTroll** [comment]
In the latest versions (don't know what version specifically, but I tried 39th and 40th version and it works there) this problem has been solved, it opens the new tab as it should.
![image](https://github.com/Alex313031/thorium/assets/71263735/d249d11c-f414-47bd-ad78-2fde1798586f)

**Comment by MagmaBro123** [comment]
This issue still ocurrs.

**Comment by vitoyucepi** [comment]
The problem was fixed in 123, 124, and 128, but reappeared in 128.
For all non-Google search engines, Thorium loads `chrome://new-tab-page-third-party/` instead of the search engine's home page.
I'd like to see something like `chrome://new-tab-page` with customization options and sites, but without Google apps and search.

**Comment by MagmaBro123** [comment]
> The problem was fixed in 123, 124, and 128, but reappeared in 128. For all non-Google search engines, Thorium loads `chrome://new-tab-page-third-party/` instead of the search engine's home page. I'd like to see something like `chrome://new-tab-page` with customization options and sites, but without Google apps and search.

Or just do what Firefox does. Have a custom Home page and let users customize what search engine is used for the search bar on it.

**Comment by faizul726** [comment]
Thorium 130 user here. facing same problem.

> ![Image](https://github.com/user-attachments/assets/cf7b055a-f428-47de-8cb7-78d08f50e626)
> Thorium 130

> ![Image](https://github.com/user-attachments/assets/1205e5e3-c741-4184-b5b6-d766ede9cf59)
> Chrome 124
