### ISSUE TITLE
FMA Instructions Support?

### ISSUE THREAD

**Issue by MedievalSteel** [Alex313031/thorium#633]
Hello, thank you excellent work!
I have an AMD CPU (FX8300) that supports FMA3 / 4 Instructions, No AVX2.
I noticed that thorium once supported FMA.
https://github.com/Alex313031/thorium/commit/2a16b6ea0ed7c0ccafc814e35a6c9a2ef573fe0d 
Why not support it now?

Thank you.

**Comment by Alex313031** [comment]
@MedievalSteel I also had an FX CPU.

AMD FX are the ONLY CPUs that have FMA, but not AVX2.

Therefore it doesn't make sense to make AVX builds with FMA, since only people with these specific CPUs would be able to run them.

You can use the AVX release. The performance difference from adding only FMA to the mix is negligible.
