### ISSUE TITLE
-

### ISSUE THREAD

**Issue by danielstreba** [Alex313031/thorium#66]
-

**Comment by Alex313031** [comment]
@danielstreba @gz83 I know they can be changed, as you can see in the TOOLBAR_TINT property when making a chrome theme, which changes the clours. I would like to add a flag which changes the colours of the .icon files, instead of hard coding them in the .icon files themselves. I understand that not everyone will want the new colours, I will work to make it an option rather than hard coded.

**Comment by Alex313031** [comment]
@danielstreba @gz83 I know they can be changed, as you can see in the TOOLBAR_TINT property when making a chrome theme, which changes the clours. I would like to add a flag which changes the colours of the .icon files, instead of hard coding them in the .icon files themselves. I understand that not everyone will want the new colours, I will work to make it an option rather than hard coded.

**Comment by Alex313031** [comment]
@danielstreba Still having trouble making this something not hard coded. Although I have reverted the reload button icon and cookies icon to blue, because using the greenish color of the chrome labs icon makes it too hard to see in light mode.

**Comment by Alex313031** [comment]
@danielstreba @gz83 Checking back in. Gz83, this is something still on the roadmap. Now that we have worked out pretty much all bugs and issues except all the win avx2 issues, I will be focusing more of my attention on developing a chrome://flags flag to toggle top bar icons. Its just a matter of finding where in source code this applies. It is not WebUI, but rather native chrome views. I feel that maybe thorium_ui_debug_shell could help with this. There is somewhere in code that sets the TINT variable, and this could be used to set the colours in the .icon files, without hard coding them in RGB like I showed you before.

**Comment by im-tem** [comment]
![image](https://user-images.githubusercontent.com/18075164/232195907-6f4524ea-484e-4738-addf-8e9b8742bfc2.png)
bump, this just doesn't work well with themes AT ALL

**Comment by l3ony2k** [comment]
Hi @Alex313031  been using Thorium for a while and having the same issue here, doesn't look good on any colored theme. Hope this can be fixed! So close to be perfect :)

**Comment by gz83** [comment]
The color of the icon changed because we hardcoded the color in the code, and we may change the icon subsequently

@Alex313031

**Comment by joaocastilho** [comment]
@Alex313031 maybe potentially revert them back to the default white while you still work on making it not hard coded?

**Comment by neo773** [comment]
Was looking to replace ungoogled chromium with Thorium but this is a blocker for me, also the contrast ratio is poor which affects accessibility

<img width="450" alt="image" src="https://github.com/Alex313031/thorium/assets/62795688/f96f3c65-6c70-496d-a705-f85fef391473">

**Comment by Alex313031** [comment]
@joaocastilho @danielstreba @im-tem @neo773  Added in all releases now that M121 is released today. Closing issue now.
