### ISSUE TITLE
anaconda.org fails to render

### ISSUE THREAD

**Issue by markounikau** [Alex313031/thorium#68]
Navigating to https://anaconda.org results in an `Aw, Snap!` page.

**Comment by midzer** [comment]
Not for me. Just tested in Incognito without any extensions using latest Thorium on debian.

**Comment by markounikau** [comment]
My Thorium version: 106.0.5212.0 (Official Build) (arm64)

**Comment by midzer** [comment]
@markounikau okay, thanks for reporting!

We're going to release a fresh M106 Thorium version for Mac soonish (probably this weekend).

**Comment by markounikau** [comment]
@midzer cool, thanks for the heads-up

**Comment by TheMadSword** [comment]
May be related to here as the problem seems to be a bit similar, so tell me if you want me to create a separate issue, but when accessing https://finance.yahoo.com/ , I get the page rendered fully for like ~0.1 / 0.2 seconds; then it goes into a "Aw, F***!", with error code 11, nothing in console.

Same Version 106.0.5212.0 (Official Build) (arm64); mac 12.5.1, M1

I also have the same problem with https://anaconda.org/

**Comment by markounikau** [comment]
Still `Aw, Snap!` for anaconda.org and finance.yahoo.com. 

Thorium 107.0.5253.0 (Official Build) (arm64), macOS 12.4.
