### ISSUE TITLE
WHY?

### ISSUE THREAD

**Issue by trytip** [Alex313031/Thorium#76]
https://i.imgur.com/BfTWJZV.jpg
![Screenshot from 2022-09-04 11-21-07](https://user-images.githubusercontent.com/34773669/188474422-bf8e10f2-eb48-4ba2-a82f-74df5a43d5a7.jpg)

https://i.imgur.com/UqCE5v0.jpg
![Selection_648](https://user-images.githubusercontent.com/34773669/188475109-6fc152e5-f1a2-45cf-8f8b-6e3c98a8ddc2.jpg)

**Comment by KarinaAE123** [comment]
How is this something worth reporting?

I can understand maybe suggesting to change the error message for broken webpages... but there is _nothing_ wrong with the credits at the bottom of the second image. Complaints like this just pointlessly clog up issue trackers.

-_-

**Comment by Alex313031** [comment]
@KarinaAE123 @trytip Yeah, what is the issue here. Is the issue because the page crashed, it says aw, fuck, or that I appended my name to the copyright.

Im going to assume all of them, so:

1. Is this page using WebRTC?
2. I added this as an easter egg, I might change it so as not to offend some humans who use thorium.
3. This is not an issue, literally every Chromium based browser adds their own copyright. AND, many (I'm looking at you, Brave, Edge, Opera) remove Chromium from it entirely, which I think is a disservice. While I put alot of work into Thorium, it is not nearly as much as the Chromium team does, so I put my name after theirs not only here, but in the headers of source code files as well. What exactly is your issue with this?
