### ISSUE TITLE
faster linker

### ISSUE THREAD

**Issue by tomByrer** [Alex313031/thorium#77]
> mold is a faster drop-in replacement for existing Unix linkers. It is several times faster than the LLVM lld linker, the second-fastest open-source linker

https://github.com/rui314/mold

**Comment by Alex313031** [comment]
@tomByrer Yes I have tried this. In fact, because of some of the issues I encountered with using LLVM LDFLAGS, I filed an issue which actually led to a patch since other people responded and had similar issues. Unfortunately, even with that patch, it still doesn't parse some of the optimization parameters I use in the main BUILD.gn for LDFLAGS and CFLAGS.

You can use mold for Chromium (and Thorium, with the optimizations removed), but I would rather have faster runtime performance, than save ~20 minutes of linking time but lose those optimization flags.

If you really want to build Thorium with mold, you will need to modify //src/build/config/compiler/BUILD.gn. If you want to do that lemme know and I can tell you which lines to remove.

**Comment by tomByrer** [comment]
Good to know, cheers~!

**Comment by Alex313031** [comment]
@t123yh Basically, if you were using thorium's build.gn, you would remove all the flags that have -mllvm in them, except the ones that are there in upstream.
