### ISSUE TITLE
Any chance to get a non deb linux build ? 

### ISSUE THREAD

**Issue by Neucher** [Alex313031/Thorium#8]
Let's be honest if you care about bleeding edge compilation optimizations your probably running arch and not debian.

**Comment by Alex313031** [comment]
I use archlabs, a bunsenlabs inspired distro built on arch, and also crunchbangplusplus.
(crunchbang was a nice minimalistic distro using the openbox WM and debian, discontinued in 2015, it spawned crunchbangplusplus and bunsenlabs,and bunsenlabs birthed archlabs. All are good. 
I actually do my thorium builds on crunchbangplusplus.
But yes I absolutely could offer a .zip that could be used portably, like with a script inside called thorium.sh or something that tells it to set the user profile dir to the same folder. This would run on any linux distro. Could also include a .desktop file for integration.

anyway here are the distros im talking about, check em out if you wish.
https://crunchbangplusplus.org/
https://archlabslinux.com/
https://www.bunsenlabs.org/

**Comment by Alex313031** [comment]
@Lehner82  @midzer  I will be making portable linux builds today. It will be a .zip with the contents of the thorium .deb, plus the wrapper script thats installed in /usr/bin, but modified to not initiate logging, and set the user profile dir to a subdir of the extracted .zip file. It will also have a .deesktop file that is likewise modified that can be put in ~/.local/share/applications/ or ~/bin/ It should run on any linux distro that has libnss3 and not too ancient core utils and glibc, etc. Tested working on debian 9, 10, 11 and ubuntu 16.04, 18.04, 20.04, 21.10 and arch 2020.05 and 2021.12 and popos 18 and garuda latest.

**Comment by Lehner82** [comment]
Cool. Definitely gonna test that.

**Comment by Alex313031** [comment]
@Lehner82 @midzer  I've made a build in Thorium Special that has a portable .zip. This build is only for Haswell and higher CPU's though. If you have a CPU older than that or older than AMD Excavator or Ryzen 1, then it's okay because the next Thorium release and from here on out will have the portable zips. I also made a commit with a new folder called portable that has the files used for portable linux releases and portable windows releases which I was already doing.

https://github.com/Alex313031/Thorium-Special/releases/tag/M99.0.4800.0

**Comment by Alex313031** [comment]
@Lehner82 Regular Thorium release with a portable .zip is now up. https://github.com/Alex313031/Thorium/releases/tag/M99.0.4803.0

**Comment by Lehner82** [comment]
I tried the portable zip on arch and fedora and it worked pretty flawlessly.

**Comment by Alex313031** [comment]
@Lehner82 Nice! Thorium-Win also has installers and a portable .zip with a readme inside if your interested. Also, im about to build with some new patches that will fix icons when distilling pages in reader mode, and adds a new UI element - a right click menu on the reload button that has three options: 'normal reload', 'hard reload', and 'clear cache and hard reload'

Also, I've been building for peoples specific architectures like haswell (for me), SSE4 (guy with 1st gen core), and tigerlake (11th gen laptop). If you'll give me your machine model no. or CPU sku number/model number, I would be more than happy to make you a personal release that will take advantage of all your cpus additional instructions

**Comment by Lehner82** [comment]
@Alex313031 The portable Thorium-Win seems to work fine too.

I have a i9 9900k skylake and a 5850u AMD Ryzen 7. Would certainly be interesting if there's any difference past avx2.

**Comment by Alex313031** [comment]
@Lehner82 Not being a reddit style know it all here, but 9xxx is coffee lake refresh (but 7th through 10th gen are all really just optimizations of skylake). Which one would you like me to make a build for?

The thing is that avx and avx2 only trigger the AVX clock offset, while avx 512 will trigger it if ANY avx 512 is used. So what @midzer  (who makes the tigerlake and macos builds) has been doing, is using a BUILD.gn I made with -march=tigerlake and -mtune=tigerlake but with extra arguments underneath it like -mno-avx-vnni and -mno-avx-512. I could do the same for you, and the result is a build that is optimized to use every instruction your processor is capable of doing, while manually disabling only specific AVX 512 instructions. I would make a BUILD.gn for you and put it in the thorium-special repo, which has build files for macos, android, and raspi, as well as other architectures. Midzer would be the one building it, because I'm on a 4790K. Clang has a weird thing where you can cross compile for anything, but when compiling for the same architecture the host machine is, the host machine has to have at least the instruction features of your target, i.e.  i would need a skylake or 5000 series ryzen. He has a tigerlake (11th gen) machine, and tigerlake has (i think) the same instructions available to it as 5000 ryzen. Just lemme know which. Also would you like a .deb or portable or both?

**Comment by Alex313031** [comment]
@Lehner82 Going back through my issues. Would you still like a custom build? If so, for which machine/cpu?

**Comment by Alex313031** [comment]
@Neucher How would you like to procede. Going back through my issues again. If this issue doesn't get a reply within a couple of weeks im going to close it due to inactivity.

**Comment by Neucher** [comment]
@Alex313031 Yes I'm closing it right now. The AVX2 build works fine.
