### ISSUE TITLE
AVX or AVX2 build?

### ISSUE THREAD

**Issue by fastcat001** [Alex313031/Thorium#83]
First things first - **A MASSIVE THANK YOU! PLEASE MAINTAIN THORIUM FOREVER**

My device supports both AVX and AVX2 Thorium builds.

Which one should I use?

**Comment by fastcat001** [comment]
@gz83 I will start using AVX2 as is.

Will new AVX2 update also update chrome store add-on and keep all my
browser settings and plugins?

I'm also interested in if add-ons auto update or not.

**Comment by fastcat001** [comment]
@gz83 I think @Alex313031 has this plugin integrated if I'm not mistaken:

https://github.com/NeverDecaf/chromium-web-store

**Comment by Alex313031** [comment]
@fastcat001 No, I do not have that plugin enabled, because I do not use the patches from ungoogled chromium that disable the web store. Thorium installs and auto updated all extensions just like google chrome, and in addition thorium has google sync just like google chrome, so if you are signed in your extensions will be synced across devices. AVX2 version should only be used on 4th gen intel and newer, amd ryzen and newer. There are some bugs in the AVX2 version for now though. I am assuming since you are asking, you are using the Windows version (since I dont make avx2 linux releases), and in that case, in the future could you make issues in thorium-win or thorium-avx2 instead of this one (the main repo/linux repo).

**Comment by G2G2G2G** [comment]
AVX2 doesn't run https://browserbench.org/JetStream/ is this closed because whatever bugs you were speaking about a few months ago were fixed? was this one of the bugs? (if so it is still around)
