### ISSUE TITLE
Adblock source dev tools

### ISSUE THREAD

**Issue by trimechee** [Alex313031/Thorium#84]
Hello, I heard that the web browser  Google Chrome Developer tools blocks ads by default without any extensions, and so I myself tested google chrome dev browser and indeed, it blocks ads, with manifest v3 and extensions adsblock will be less effective, can Thorium browser integrate the Google Chrome Dev browser code to block ads at source and without the need for adblock extensions please?

https://www.google.com/chrome/dev/

**Comment by Velocet** [comment]
This is already implemented and activated as it is a standard feature in Chromium/Chrome: [Where's the Ad Blocker On Google Chrome?](https://brave.com/learn/disable-ad-blocker-on-chrome/)

But maybe it's possible to alter the function of this builtin AdBlocker? Since most people use uBlock it should either be disabled or replaced by uBlock.

**Comment by trimechee** [comment]
Sadly cchrome developer tool browser doesn't block ads any more :(
